[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Function calling with constrained decoding using a small LLM"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pydantic>=2.0,<3.0",
    "torch>=2.0.0",
    "transformers>=4.40.0",
]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
]

[[tool.mypy.overrides]]
module = ["llm_sdk", "llm_sdk.*"]
follow_imports = "skip"
